services:
  api:
    build: .
    env_file:
      - .env
    command: ["./pulse_watch"]
    ports:
      - "8080:8080"

  background:
    build: .
    env_file:
      - .env
    command: ["./pulse_watch_background"]

  queues:
    build: .
    env_file:
      - .env
    command: ["./pulse_watch_queues"]