// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vekshinnikita/pulse_watch/internal/repository (interfaces: AlertRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_alert_repository.go -package=mock_repository . AlertRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entities "github.com/vekshinnikita/pulse_watch/internal/entities"
	dtos "github.com/vekshinnikita/pulse_watch/internal/entities/dtos"
	models "github.com/vekshinnikita/pulse_watch/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAlertRepository is a mock of AlertRepository interface.
type MockAlertRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAlertRepositoryMockRecorder
	isgomock struct{}
}

// MockAlertRepositoryMockRecorder is the mock recorder for MockAlertRepository.
type MockAlertRepositoryMockRecorder struct {
	mock *MockAlertRepository
}

// NewMockAlertRepository creates a new mock instance.
func NewMockAlertRepository(ctrl *gomock.Controller) *MockAlertRepository {
	mock := &MockAlertRepository{ctrl: ctrl}
	mock.recorder = &MockAlertRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlertRepository) EXPECT() *MockAlertRepositoryMockRecorder {
	return m.recorder
}

// CreateAlertRule mocks base method.
func (m *MockAlertRepository) CreateAlertRule(ctx context.Context, data *entities.CreateAlertRule) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAlertRule", ctx, data)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAlertRule indicates an expected call of CreateAlertRule.
func (mr *MockAlertRepositoryMockRecorder) CreateAlertRule(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAlertRule", reflect.TypeOf((*MockAlertRepository)(nil).CreateAlertRule), ctx, data)
}

// CreateAlerts mocks base method.
func (m *MockAlertRepository) CreateAlerts(ctx context.Context, data []dtos.CreateAlert) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAlerts", ctx, data)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAlerts indicates an expected call of CreateAlerts.
func (mr *MockAlertRepositoryMockRecorder) CreateAlerts(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAlerts", reflect.TypeOf((*MockAlertRepository)(nil).CreateAlerts), ctx, data)
}

// DeleteAlertRule mocks base method.
func (m *MockAlertRepository) DeleteAlertRule(ctx context.Context, ruleId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAlertRule", ctx, ruleId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAlertRule indicates an expected call of DeleteAlertRule.
func (mr *MockAlertRepositoryMockRecorder) DeleteAlertRule(ctx, ruleId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAlertRule", reflect.TypeOf((*MockAlertRepository)(nil).DeleteAlertRule), ctx, ruleId)
}

// GetAppRules mocks base method.
func (m *MockAlertRepository) GetAppRules(ctx context.Context, appId int) ([]models.AlertRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppRules", ctx, appId)
	ret0, _ := ret[0].([]models.AlertRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppRules indicates an expected call of GetAppRules.
func (mr *MockAlertRepositoryMockRecorder) GetAppRules(ctx, appId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppRules", reflect.TypeOf((*MockAlertRepository)(nil).GetAppRules), ctx, appId)
}

// GetAppRulesPaginated mocks base method.
func (m *MockAlertRepository) GetAppRulesPaginated(ctx context.Context, p *entities.PaginationData, appId int) (*entities.PaginationResult[models.AlertRule], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppRulesPaginated", ctx, p, appId)
	ret0, _ := ret[0].(*entities.PaginationResult[models.AlertRule])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppRulesPaginated indicates an expected call of GetAppRulesPaginated.
func (mr *MockAlertRepositoryMockRecorder) GetAppRulesPaginated(ctx, p, appId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppRulesPaginated", reflect.TypeOf((*MockAlertRepository)(nil).GetAppRulesPaginated), ctx, p, appId)
}

// GetFullAlertsByIds mocks base method.
func (m *MockAlertRepository) GetFullAlertsByIds(ctx context.Context, alertIds []int) ([]models.AlertFull, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFullAlertsByIds", ctx, alertIds)
	ret0, _ := ret[0].([]models.AlertFull)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFullAlertsByIds indicates an expected call of GetFullAlertsByIds.
func (mr *MockAlertRepositoryMockRecorder) GetFullAlertsByIds(ctx, alertIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFullAlertsByIds", reflect.TypeOf((*MockAlertRepository)(nil).GetFullAlertsByIds), ctx, alertIds)
}

// GetRecentAlertsByRules mocks base method.
func (m *MockAlertRepository) GetRecentAlertsByRules(ctx context.Context, data *dtos.GetRecentAlerts) ([]models.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentAlertsByRules", ctx, data)
	ret0, _ := ret[0].([]models.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentAlertsByRules indicates an expected call of GetRecentAlertsByRules.
func (mr *MockAlertRepositoryMockRecorder) GetRecentAlertsByRules(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentAlertsByRules", reflect.TypeOf((*MockAlertRepository)(nil).GetRecentAlertsByRules), ctx, data)
}

// GetRule mocks base method.
func (m *MockAlertRepository) GetRule(ctx context.Context, ruleId int) (*models.AlertRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRule", ctx, ruleId)
	ret0, _ := ret[0].(*models.AlertRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRule indicates an expected call of GetRule.
func (mr *MockAlertRepositoryMockRecorder) GetRule(ctx, ruleId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRule", reflect.TypeOf((*MockAlertRepository)(nil).GetRule), ctx, ruleId)
}

// SetResolvedAlerts mocks base method.
func (m *MockAlertRepository) SetResolvedAlerts(ctx context.Context, alertIds []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetResolvedAlerts", ctx, alertIds)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetResolvedAlerts indicates an expected call of SetResolvedAlerts.
func (mr *MockAlertRepositoryMockRecorder) SetResolvedAlerts(ctx, alertIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetResolvedAlerts", reflect.TypeOf((*MockAlertRepository)(nil).SetResolvedAlerts), ctx, alertIds)
}

// UpdateAlertRule mocks base method.
func (m *MockAlertRepository) UpdateAlertRule(ctx context.Context, ruleId int, data *entities.UpdateAlertRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAlertRule", ctx, ruleId, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAlertRule indicates an expected call of UpdateAlertRule.
func (mr *MockAlertRepositoryMockRecorder) UpdateAlertRule(ctx, ruleId, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAlertRule", reflect.TypeOf((*MockAlertRepository)(nil).UpdateAlertRule), ctx, ruleId, data)
}
