// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vekshinnikita/pulse_watch/internal/repository (interfaces: AuthRedisRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_auth_redis_repository.go -package=mock_repository . AuthRedisRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	models "github.com/vekshinnikita/pulse_watch/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthRedisRepository is a mock of AuthRedisRepository interface.
type MockAuthRedisRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRedisRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthRedisRepositoryMockRecorder is the mock recorder for MockAuthRedisRepository.
type MockAuthRedisRepositoryMockRecorder struct {
	mock *MockAuthRedisRepository
}

// NewMockAuthRedisRepository creates a new mock instance.
func NewMockAuthRedisRepository(ctrl *gomock.Controller) *MockAuthRedisRepository {
	mock := &MockAuthRedisRepository{ctrl: ctrl}
	mock.recorder = &MockAuthRedisRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRedisRepository) EXPECT() *MockAuthRedisRepositoryMockRecorder {
	return m.recorder
}

// CheckAnyPermissions mocks base method.
func (m *MockAuthRedisRepository) CheckAnyPermissions(ctx context.Context, roleCode string, permissionCodes []string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAnyPermissions", ctx, roleCode, permissionCodes)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAnyPermissions indicates an expected call of CheckAnyPermissions.
func (mr *MockAuthRedisRepositoryMockRecorder) CheckAnyPermissions(ctx, roleCode, permissionCodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAnyPermissions", reflect.TypeOf((*MockAuthRedisRepository)(nil).CheckAnyPermissions), ctx, roleCode, permissionCodes)
}

// CheckPermission mocks base method.
func (m *MockAuthRedisRepository) CheckPermission(ctx context.Context, roleCode, permissionCode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPermission", ctx, roleCode, permissionCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPermission indicates an expected call of CheckPermission.
func (mr *MockAuthRedisRepositoryMockRecorder) CheckPermission(ctx, roleCode, permissionCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPermission", reflect.TypeOf((*MockAuthRedisRepository)(nil).CheckPermission), ctx, roleCode, permissionCode)
}

// LoadPermissions mocks base method.
func (m *MockAuthRedisRepository) LoadPermissions(ctx context.Context, roleCode string, permissions []models.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadPermissions", ctx, roleCode, permissions)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadPermissions indicates an expected call of LoadPermissions.
func (mr *MockAuthRedisRepositoryMockRecorder) LoadPermissions(ctx, roleCode, permissions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadPermissions", reflect.TypeOf((*MockAuthRedisRepository)(nil).LoadPermissions), ctx, roleCode, permissions)
}
