// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vekshinnikita/pulse_watch/internal/repository (interfaces: MetricRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_metric_repository.go -package=mock_repository . MetricRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	constants "github.com/vekshinnikita/pulse_watch/internal/constants"
	entities "github.com/vekshinnikita/pulse_watch/internal/entities"
	dtos "github.com/vekshinnikita/pulse_watch/internal/entities/dtos"
	models "github.com/vekshinnikita/pulse_watch/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricRepository is a mock of MetricRepository interface.
type MockMetricRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricRepositoryMockRecorder
	isgomock struct{}
}

// MockMetricRepositoryMockRecorder is the mock recorder for MockMetricRepository.
type MockMetricRepositoryMockRecorder struct {
	mock *MockMetricRepository
}

// NewMockMetricRepository creates a new mock instance.
func NewMockMetricRepository(ctrl *gomock.Controller) *MockMetricRepository {
	mock := &MockMetricRepository{ctrl: ctrl}
	mock.recorder = &MockMetricRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricRepository) EXPECT() *MockMetricRepositoryMockRecorder {
	return m.recorder
}

// ClearMetrics mocks base method.
func (m *MockMetricRepository) ClearMetrics(ctx context.Context, data dtos.ClearMetrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearMetrics", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearMetrics indicates an expected call of ClearMetrics.
func (mr *MockMetricRepositoryMockRecorder) ClearMetrics(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearMetrics", reflect.TypeOf((*MockMetricRepository)(nil).ClearMetrics), ctx, data)
}

// CreateAppMetrics mocks base method.
func (m *MockMetricRepository) CreateAppMetrics(ctx context.Context, data []dtos.CreateAppMetric) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAppMetrics", ctx, data)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAppMetrics indicates an expected call of CreateAppMetrics.
func (mr *MockMetricRepositoryMockRecorder) CreateAppMetrics(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppMetrics", reflect.TypeOf((*MockMetricRepository)(nil).CreateAppMetrics), ctx, data)
}

// GetAggregatedAppMetricsByPeriod mocks base method.
func (m *MockMetricRepository) GetAggregatedAppMetricsByPeriod(ctx context.Context, appIds []int, periodType constants.PeriodType, startTime, endTime time.Time) ([]dtos.AggregatedAppMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAggregatedAppMetricsByPeriod", ctx, appIds, periodType, startTime, endTime)
	ret0, _ := ret[0].([]dtos.AggregatedAppMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAggregatedAppMetricsByPeriod indicates an expected call of GetAggregatedAppMetricsByPeriod.
func (mr *MockMetricRepositoryMockRecorder) GetAggregatedAppMetricsByPeriod(ctx, appIds, periodType, startTime, endTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAggregatedAppMetricsByPeriod", reflect.TypeOf((*MockMetricRepository)(nil).GetAggregatedAppMetricsByPeriod), ctx, appIds, periodType, startTime, endTime)
}

// GetAggregatedMetricsForAlert mocks base method.
func (m *MockMetricRepository) GetAggregatedMetricsForAlert(ctx context.Context, appId int, data []dtos.AggregateMetricsForAlert) ([]dtos.AggregatedAppMetricForAlert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAggregatedMetricsForAlert", ctx, appId, data)
	ret0, _ := ret[0].([]dtos.AggregatedAppMetricForAlert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAggregatedMetricsForAlert indicates an expected call of GetAggregatedMetricsForAlert.
func (mr *MockMetricRepositoryMockRecorder) GetAggregatedMetricsForAlert(ctx, appId, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAggregatedMetricsForAlert", reflect.TypeOf((*MockMetricRepository)(nil).GetAggregatedMetricsForAlert), ctx, appId, data)
}

// GetMetrics mocks base method.
func (m *MockMetricRepository) GetMetrics(ctx context.Context, appId int, data *entities.GetMetricsData) ([]models.AppMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics", ctx, appId, data)
	ret0, _ := ret[0].([]models.AppMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockMetricRepositoryMockRecorder) GetMetrics(ctx, appId, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*MockMetricRepository)(nil).GetMetrics), ctx, appId, data)
}
