// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vekshinnikita/pulse_watch/internal/repository (interfaces: AppRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_app_repository.go -package=mock_repository . AppRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entities "github.com/vekshinnikita/pulse_watch/internal/entities"
	dtos "github.com/vekshinnikita/pulse_watch/internal/entities/dtos"
	models "github.com/vekshinnikita/pulse_watch/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAppRepository is a mock of AppRepository interface.
type MockAppRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAppRepositoryMockRecorder
	isgomock struct{}
}

// MockAppRepositoryMockRecorder is the mock recorder for MockAppRepository.
type MockAppRepositoryMockRecorder struct {
	mock *MockAppRepository
}

// NewMockAppRepository creates a new mock instance.
func NewMockAppRepository(ctrl *gomock.Controller) *MockAppRepository {
	mock := &MockAppRepository{ctrl: ctrl}
	mock.recorder = &MockAppRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppRepository) EXPECT() *MockAppRepositoryMockRecorder {
	return m.recorder
}

// CheckApiKey mocks base method.
func (m *MockAppRepository) CheckApiKey(ctx context.Context, keyHash string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckApiKey", ctx, keyHash)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckApiKey indicates an expected call of CheckApiKey.
func (mr *MockAppRepositoryMockRecorder) CheckApiKey(ctx, keyHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckApiKey", reflect.TypeOf((*MockAppRepository)(nil).CheckApiKey), ctx, keyHash)
}

// CreateApiKey mocks base method.
func (m *MockAppRepository) CreateApiKey(ctx context.Context, data *dtos.CreateApiKeyData) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApiKey", ctx, data)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateApiKey indicates an expected call of CreateApiKey.
func (mr *MockAppRepositoryMockRecorder) CreateApiKey(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApiKey", reflect.TypeOf((*MockAppRepository)(nil).CreateApiKey), ctx, data)
}

// CreateApp mocks base method.
func (m *MockAppRepository) CreateApp(ctx context.Context, data *entities.CreateAppData) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApp", ctx, data)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateApp indicates an expected call of CreateApp.
func (mr *MockAppRepositoryMockRecorder) CreateApp(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApp", reflect.TypeOf((*MockAppRepository)(nil).CreateApp), ctx, data)
}

// DeleteApp mocks base method.
func (m *MockAppRepository) DeleteApp(ctx context.Context, appId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteApp", ctx, appId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteApp indicates an expected call of DeleteApp.
func (mr *MockAppRepositoryMockRecorder) DeleteApp(ctx, appId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApp", reflect.TypeOf((*MockAppRepository)(nil).DeleteApp), ctx, appId)
}

// GetApp mocks base method.
func (m *MockAppRepository) GetApp(ctx context.Context, appId int) (*models.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApp", ctx, appId)
	ret0, _ := ret[0].(*models.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApp indicates an expected call of GetApp.
func (mr *MockAppRepositoryMockRecorder) GetApp(ctx, appId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApp", reflect.TypeOf((*MockAppRepository)(nil).GetApp), ctx, appId)
}

// GetAppApiKeysPaginated mocks base method.
func (m *MockAppRepository) GetAppApiKeysPaginated(ctx context.Context, p *entities.PaginationData, appId int) (*entities.PaginationResult[models.ApiKey], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppApiKeysPaginated", ctx, p, appId)
	ret0, _ := ret[0].(*entities.PaginationResult[models.ApiKey])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppApiKeysPaginated indicates an expected call of GetAppApiKeysPaginated.
func (mr *MockAppRepositoryMockRecorder) GetAppApiKeysPaginated(ctx, p, appId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppApiKeysPaginated", reflect.TypeOf((*MockAppRepository)(nil).GetAppApiKeysPaginated), ctx, p, appId)
}

// GetAppIds mocks base method.
func (m *MockAppRepository) GetAppIds(ctx context.Context) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppIds", ctx)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppIds indicates an expected call of GetAppIds.
func (mr *MockAppRepositoryMockRecorder) GetAppIds(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppIds", reflect.TypeOf((*MockAppRepository)(nil).GetAppIds), ctx)
}

// RevokeApiKey mocks base method.
func (m *MockAppRepository) RevokeApiKey(ctx context.Context, appId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeApiKey", ctx, appId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeApiKey indicates an expected call of RevokeApiKey.
func (mr *MockAppRepositoryMockRecorder) RevokeApiKey(ctx, appId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeApiKey", reflect.TypeOf((*MockAppRepository)(nil).RevokeApiKey), ctx, appId)
}
