// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vekshinnikita/pulse_watch/internal/repository (interfaces: MessageProducer)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_message_producer.go -package=mock_repository . MessageProducer
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	kafka "github.com/confluentinc/confluent-kafka-go/kafka"
	dtos "github.com/vekshinnikita/pulse_watch/internal/entities/dtos"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageProducer is a mock of MessageProducer interface.
type MockMessageProducer struct {
	ctrl     *gomock.Controller
	recorder *MockMessageProducerMockRecorder
	isgomock struct{}
}

// MockMessageProducerMockRecorder is the mock recorder for MockMessageProducer.
type MockMessageProducerMockRecorder struct {
	mock *MockMessageProducer
}

// NewMockMessageProducer creates a new mock instance.
func NewMockMessageProducer(ctrl *gomock.Controller) *MockMessageProducer {
	mock := &MockMessageProducer{ctrl: ctrl}
	mock.recorder = &MockMessageProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageProducer) EXPECT() *MockMessageProducerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockMessageProducer) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockMessageProducerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMessageProducer)(nil).Close))
}

// Publish mocks base method.
func (m *MockMessageProducer) Publish(ctx context.Context, options *dtos.MessageOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, options)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockMessageProducerMockRecorder) Publish(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockMessageProducer)(nil).Publish), ctx, options)
}

// PublishRaw mocks base method.
func (m *MockMessageProducer) PublishRaw(ctx context.Context, message *kafka.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishRaw", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishRaw indicates an expected call of PublishRaw.
func (mr *MockMessageProducerMockRecorder) PublishRaw(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishRaw", reflect.TypeOf((*MockMessageProducer)(nil).PublishRaw), ctx, message)
}
