// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vekshinnikita/pulse_watch/internal/repository (interfaces: LogsESRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_logs_es_repository.go -package=mock_repository . LogsESRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entities "github.com/vekshinnikita/pulse_watch/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockLogsESRepository is a mock of LogsESRepository interface.
type MockLogsESRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLogsESRepositoryMockRecorder
	isgomock struct{}
}

// MockLogsESRepositoryMockRecorder is the mock recorder for MockLogsESRepository.
type MockLogsESRepositoryMockRecorder struct {
	mock *MockLogsESRepository
}

// NewMockLogsESRepository creates a new mock instance.
func NewMockLogsESRepository(ctrl *gomock.Controller) *MockLogsESRepository {
	mock := &MockLogsESRepository{ctrl: ctrl}
	mock.recorder = &MockLogsESRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogsESRepository) EXPECT() *MockLogsESRepositoryMockRecorder {
	return m.recorder
}

// BulkSave mocks base method.
func (m *MockLogsESRepository) BulkSave(ctx context.Context, logs []entities.EnrichedAppLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkSave", ctx, logs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkSave indicates an expected call of BulkSave.
func (mr *MockLogsESRepositoryMockRecorder) BulkSave(ctx, logs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkSave", reflect.TypeOf((*MockLogsESRepository)(nil).BulkSave), ctx, logs)
}

// SearchPaginated mocks base method.
func (m *MockLogsESRepository) SearchPaginated(ctx context.Context, data *entities.SearchLogData) (*entities.PaginationResult[entities.EnrichedAppLog], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchPaginated", ctx, data)
	ret0, _ := ret[0].(*entities.PaginationResult[entities.EnrichedAppLog])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPaginated indicates an expected call of SearchPaginated.
func (mr *MockLogsESRepositoryMockRecorder) SearchPaginated(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPaginated", reflect.TypeOf((*MockLogsESRepository)(nil).SearchPaginated), ctx, data)
}
