// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vekshinnikita/pulse_watch/internal/repository (interfaces: AnalyticsRedisRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_analytics_redis_repository.go -package=mock_repository . AnalyticsRedisRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	redis "github.com/go-redis/redis/v8"
	constants "github.com/vekshinnikita/pulse_watch/internal/constants"
	dtos "github.com/vekshinnikita/pulse_watch/internal/entities/dtos"
	gomock "go.uber.org/mock/gomock"
)

// MockAnalyticsRedisRepository is a mock of AnalyticsRedisRepository interface.
type MockAnalyticsRedisRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsRedisRepositoryMockRecorder
	isgomock struct{}
}

// MockAnalyticsRedisRepositoryMockRecorder is the mock recorder for MockAnalyticsRedisRepository.
type MockAnalyticsRedisRepositoryMockRecorder struct {
	mock *MockAnalyticsRedisRepository
}

// NewMockAnalyticsRedisRepository creates a new mock instance.
func NewMockAnalyticsRedisRepository(ctrl *gomock.Controller) *MockAnalyticsRedisRepository {
	mock := &MockAnalyticsRedisRepository{ctrl: ctrl}
	mock.recorder = &MockAnalyticsRedisRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyticsRedisRepository) EXPECT() *MockAnalyticsRedisRepositoryMockRecorder {
	return m.recorder
}

// AddExpire mocks base method.
func (m *MockAnalyticsRedisRepository) AddExpire(ctx context.Context, name string, expire time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddExpire", ctx, name, expire)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddExpire indicates an expected call of AddExpire.
func (mr *MockAnalyticsRedisRepositoryMockRecorder) AddExpire(ctx, name, expire any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddExpire", reflect.TypeOf((*MockAnalyticsRedisRepository)(nil).AddExpire), ctx, name, expire)
}

// AddMetric mocks base method.
func (m *MockAnalyticsRedisRepository) AddMetric(ctx context.Context, name, key string, value int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMetric", ctx, name, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMetric indicates an expected call of AddMetric.
func (mr *MockAnalyticsRedisRepositoryMockRecorder) AddMetric(ctx, name, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMetric", reflect.TypeOf((*MockAnalyticsRedisRepository)(nil).AddMetric), ctx, name, key, value)
}

// AddUniqueMetric mocks base method.
func (m *MockAnalyticsRedisRepository) AddUniqueMetric(ctx context.Context, name string, metric *dtos.UniqueMetric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUniqueMetric", ctx, name, metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUniqueMetric indicates an expected call of AddUniqueMetric.
func (mr *MockAnalyticsRedisRepositoryMockRecorder) AddUniqueMetric(ctx, name, metric any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUniqueMetric", reflect.TypeOf((*MockAnalyticsRedisRepository)(nil).AddUniqueMetric), ctx, name, metric)
}

// GetAggregatedLiveMetrics mocks base method.
func (m *MockAnalyticsRedisRepository) GetAggregatedLiveMetrics(ctx context.Context, appId int, start, end time.Time) ([]dtos.AggregatedMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAggregatedLiveMetrics", ctx, appId, start, end)
	ret0, _ := ret[0].([]dtos.AggregatedMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAggregatedLiveMetrics indicates an expected call of GetAggregatedLiveMetrics.
func (mr *MockAnalyticsRedisRepositoryMockRecorder) GetAggregatedLiveMetrics(ctx, appId, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAggregatedLiveMetrics", reflect.TypeOf((*MockAnalyticsRedisRepository)(nil).GetAggregatedLiveMetrics), ctx, appId, start, end)
}

// GetAggregatedMetricsByApps mocks base method.
func (m *MockAnalyticsRedisRepository) GetAggregatedMetricsByApps(ctx context.Context, appIds []int, windowStart, windowEnd time.Time) ([]dtos.AggregatedMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAggregatedMetricsByApps", ctx, appIds, windowStart, windowEnd)
	ret0, _ := ret[0].([]dtos.AggregatedMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAggregatedMetricsByApps indicates an expected call of GetAggregatedMetricsByApps.
func (mr *MockAnalyticsRedisRepositoryMockRecorder) GetAggregatedMetricsByApps(ctx, appIds, windowStart, windowEnd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAggregatedMetricsByApps", reflect.TypeOf((*MockAnalyticsRedisRepository)(nil).GetAggregatedMetricsByApps), ctx, appIds, windowStart, windowEnd)
}

// GetAggregatedUniqueMetricsByApps mocks base method.
func (m *MockAnalyticsRedisRepository) GetAggregatedUniqueMetricsByApps(ctx context.Context, appIds []int, periodType constants.PeriodType, windowStart time.Time) ([]dtos.AggregatedMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAggregatedUniqueMetricsByApps", ctx, appIds, periodType, windowStart)
	ret0, _ := ret[0].([]dtos.AggregatedMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAggregatedUniqueMetricsByApps indicates an expected call of GetAggregatedUniqueMetricsByApps.
func (mr *MockAnalyticsRedisRepositoryMockRecorder) GetAggregatedUniqueMetricsByApps(ctx, appIds, periodType, windowStart any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAggregatedUniqueMetricsByApps", reflect.TypeOf((*MockAnalyticsRedisRepository)(nil).GetAggregatedUniqueMetricsByApps), ctx, appIds, periodType, windowStart)
}

// GetKeysCursor mocks base method.
func (m *MockAnalyticsRedisRepository) GetKeysCursor(ctx context.Context, cursor uint64, pattern string, count int) ([]string, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeysCursor", ctx, cursor, pattern, count)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetKeysCursor indicates an expected call of GetKeysCursor.
func (mr *MockAnalyticsRedisRepositoryMockRecorder) GetKeysCursor(ctx, cursor, pattern, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeysCursor", reflect.TypeOf((*MockAnalyticsRedisRepository)(nil).GetKeysCursor), ctx, cursor, pattern, count)
}

// GetLiveMetrics mocks base method.
func (m *MockAnalyticsRedisRepository) GetLiveMetrics(ctx context.Context, data *dtos.GetLiveMetricsData) ([]dtos.LiveMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLiveMetrics", ctx, data)
	ret0, _ := ret[0].([]dtos.LiveMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLiveMetrics indicates an expected call of GetLiveMetrics.
func (mr *MockAnalyticsRedisRepositoryMockRecorder) GetLiveMetrics(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLiveMetrics", reflect.TypeOf((*MockAnalyticsRedisRepository)(nil).GetLiveMetrics), ctx, data)
}

// PublishToChannel mocks base method.
func (m *MockAnalyticsRedisRepository) PublishToChannel(ctx context.Context, channelId string, data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishToChannel", ctx, channelId, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishToChannel indicates an expected call of PublishToChannel.
func (mr *MockAnalyticsRedisRepositoryMockRecorder) PublishToChannel(ctx, channelId, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishToChannel", reflect.TypeOf((*MockAnalyticsRedisRepository)(nil).PublishToChannel), ctx, channelId, data)
}

// SubscribePubSub mocks base method.
func (m *MockAnalyticsRedisRepository) SubscribePubSub(ctx context.Context, channelId string) (*redis.PubSub, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribePubSub", ctx, channelId)
	ret0, _ := ret[0].(*redis.PubSub)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribePubSub indicates an expected call of SubscribePubSub.
func (mr *MockAnalyticsRedisRepositoryMockRecorder) SubscribePubSub(ctx, channelId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribePubSub", reflect.TypeOf((*MockAnalyticsRedisRepository)(nil).SubscribePubSub), ctx, channelId)
}

// SubscribeStream mocks base method.
func (m *MockAnalyticsRedisRepository) SubscribeStream(ctx context.Context, channelIds ...string) ([]redis.XStream, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range channelIds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeStream", varargs...)
	ret0, _ := ret[0].([]redis.XStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeStream indicates an expected call of SubscribeStream.
func (mr *MockAnalyticsRedisRepositoryMockRecorder) SubscribeStream(ctx any, channelIds ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, channelIds...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeStream", reflect.TypeOf((*MockAnalyticsRedisRepository)(nil).SubscribeStream), varargs...)
}

// TransferLiveMetricsToStreams mocks base method.
func (m *MockAnalyticsRedisRepository) TransferLiveMetricsToStreams(ctx context.Context, metricKeys []string) ([]dtos.TransferredMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferLiveMetricsToStreams", ctx, metricKeys)
	ret0, _ := ret[0].([]dtos.TransferredMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransferLiveMetricsToStreams indicates an expected call of TransferLiveMetricsToStreams.
func (mr *MockAnalyticsRedisRepositoryMockRecorder) TransferLiveMetricsToStreams(ctx, metricKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferLiveMetricsToStreams", reflect.TypeOf((*MockAnalyticsRedisRepository)(nil).TransferLiveMetricsToStreams), ctx, metricKeys)
}
