// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vekshinnikita/pulse_watch/internal/repository (interfaces: LogRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_log_repository.go -package=mock_repository . LogRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entities "github.com/vekshinnikita/pulse_watch/internal/entities"
	dtos "github.com/vekshinnikita/pulse_watch/internal/entities/dtos"
	models "github.com/vekshinnikita/pulse_watch/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockLogRepository is a mock of LogRepository interface.
type MockLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLogRepositoryMockRecorder
	isgomock struct{}
}

// MockLogRepositoryMockRecorder is the mock recorder for MockLogRepository.
type MockLogRepositoryMockRecorder struct {
	mock *MockLogRepository
}

// NewMockLogRepository creates a new mock instance.
func NewMockLogRepository(ctrl *gomock.Controller) *MockLogRepository {
	mock := &MockLogRepository{ctrl: ctrl}
	mock.recorder = &MockLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogRepository) EXPECT() *MockLogRepositoryMockRecorder {
	return m.recorder
}

// CreateMetaVars mocks base method.
func (m *MockLogRepository) CreateMetaVars(ctx context.Context, data []dtos.CreateMetaVar) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMetaVars", ctx, data)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMetaVars indicates an expected call of CreateMetaVars.
func (mr *MockLogRepositoryMockRecorder) CreateMetaVars(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMetaVars", reflect.TypeOf((*MockLogRepository)(nil).CreateMetaVars), ctx, data)
}

// GetAppLogMetaVarsByCodes mocks base method.
func (m *MockLogRepository) GetAppLogMetaVarsByCodes(ctx context.Context, appId int, varCodes []string) ([]models.LogMetaVar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppLogMetaVarsByCodes", ctx, appId, varCodes)
	ret0, _ := ret[0].([]models.LogMetaVar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppLogMetaVarsByCodes indicates an expected call of GetAppLogMetaVarsByCodes.
func (mr *MockLogRepositoryMockRecorder) GetAppLogMetaVarsByCodes(ctx, appId, varCodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppLogMetaVarsByCodes", reflect.TypeOf((*MockLogRepository)(nil).GetAppLogMetaVarsByCodes), ctx, appId, varCodes)
}

// GetMetaVarsPaginated mocks base method.
func (m *MockLogRepository) GetMetaVarsPaginated(ctx context.Context, pagination *entities.PaginationData, appId *int) (*entities.PaginationResult[entities.LogMetaVarResult], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetaVarsPaginated", ctx, pagination, appId)
	ret0, _ := ret[0].(*entities.PaginationResult[entities.LogMetaVarResult])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetaVarsPaginated indicates an expected call of GetMetaVarsPaginated.
func (mr *MockLogRepositoryMockRecorder) GetMetaVarsPaginated(ctx, pagination, appId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetaVarsPaginated", reflect.TypeOf((*MockLogRepository)(nil).GetMetaVarsPaginated), ctx, pagination, appId)
}
