// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vekshinnikita/pulse_watch/internal/service/auth (interfaces: CheckPermissionUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_usecases.go -package=mock_auth_service . CheckPermissionUseCase
//

// Package mock_auth_service is a generated GoMock package.
package mock_auth_service

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCheckPermissionUseCase is a mock of CheckPermissionUseCase interface.
type MockCheckPermissionUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCheckPermissionUseCaseMockRecorder
	isgomock struct{}
}

// MockCheckPermissionUseCaseMockRecorder is the mock recorder for MockCheckPermissionUseCase.
type MockCheckPermissionUseCaseMockRecorder struct {
	mock *MockCheckPermissionUseCase
}

// NewMockCheckPermissionUseCase creates a new mock instance.
func NewMockCheckPermissionUseCase(ctrl *gomock.Controller) *MockCheckPermissionUseCase {
	mock := &MockCheckPermissionUseCase{ctrl: ctrl}
	mock.recorder = &MockCheckPermissionUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckPermissionUseCase) EXPECT() *MockCheckPermissionUseCaseMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockCheckPermissionUseCase) Check(ctx context.Context, roleCode, permissionCode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, roleCode, permissionCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockCheckPermissionUseCaseMockRecorder) Check(ctx, roleCode, permissionCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockCheckPermissionUseCase)(nil).Check), ctx, roleCode, permissionCode)
}

// CheckAny mocks base method.
func (m *MockCheckPermissionUseCase) CheckAny(ctx context.Context, roleCode string, permissionCodes []string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAny", ctx, roleCode, permissionCodes)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAny indicates an expected call of CheckAny.
func (mr *MockCheckPermissionUseCaseMockRecorder) CheckAny(ctx, roleCode, permissionCodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAny", reflect.TypeOf((*MockCheckPermissionUseCase)(nil).CheckAny), ctx, roleCode, permissionCodes)
}
