// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vekshinnikita/pulse_watch/internal/service/auth (interfaces: TokenProvider)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_token_provider.go -package=mock_auth_service . TokenProvider
//

// Package mock_auth_service is a generated GoMock package.
package mock_auth_service

import (
	reflect "reflect"

	jwt "github.com/dgrijalva/jwt-go"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenProvider is a mock of TokenProvider interface.
type MockTokenProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTokenProviderMockRecorder
	isgomock struct{}
}

// MockTokenProviderMockRecorder is the mock recorder for MockTokenProvider.
type MockTokenProviderMockRecorder struct {
	mock *MockTokenProvider
}

// NewMockTokenProvider creates a new mock instance.
func NewMockTokenProvider(ctrl *gomock.Controller) *MockTokenProvider {
	mock := &MockTokenProvider{ctrl: ctrl}
	mock.recorder = &MockTokenProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenProvider) EXPECT() *MockTokenProviderMockRecorder {
	return m.recorder
}

// NewWithClaims mocks base method.
func (m *MockTokenProvider) NewWithClaims(method jwt.SigningMethod, claims jwt.Claims) *jwt.Token {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewWithClaims", method, claims)
	ret0, _ := ret[0].(*jwt.Token)
	return ret0
}

// NewWithClaims indicates an expected call of NewWithClaims.
func (mr *MockTokenProviderMockRecorder) NewWithClaims(method, claims any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewWithClaims", reflect.TypeOf((*MockTokenProvider)(nil).NewWithClaims), method, claims)
}

// ParseWithClaims mocks base method.
func (m *MockTokenProvider) ParseWithClaims(tokenString string, claims jwt.Claims, keyFunc jwt.Keyfunc) (*jwt.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseWithClaims", tokenString, claims, keyFunc)
	ret0, _ := ret[0].(*jwt.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseWithClaims indicates an expected call of ParseWithClaims.
func (mr *MockTokenProviderMockRecorder) ParseWithClaims(tokenString, claims, keyFunc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseWithClaims", reflect.TypeOf((*MockTokenProvider)(nil).ParseWithClaims), tokenString, claims, keyFunc)
}
