// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vekshinnikita/pulse_watch/internal/service (interfaces: MetricService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_metric_service.go -package=mock_service . MetricService
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"
	time "time"

	constants "github.com/vekshinnikita/pulse_watch/internal/constants"
	entities "github.com/vekshinnikita/pulse_watch/internal/entities"
	dtos "github.com/vekshinnikita/pulse_watch/internal/entities/dtos"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricService is a mock of MetricService interface.
type MockMetricService struct {
	ctrl     *gomock.Controller
	recorder *MockMetricServiceMockRecorder
	isgomock struct{}
}

// MockMetricServiceMockRecorder is the mock recorder for MockMetricService.
type MockMetricServiceMockRecorder struct {
	mock *MockMetricService
}

// NewMockMetricService creates a new mock instance.
func NewMockMetricService(ctrl *gomock.Controller) *MockMetricService {
	mock := &MockMetricService{ctrl: ctrl}
	mock.recorder = &MockMetricServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricService) EXPECT() *MockMetricServiceMockRecorder {
	return m.recorder
}

// AggregateOneMinuteMetrics mocks base method.
func (m *MockMetricService) AggregateOneMinuteMetrics(ctx context.Context, appIds []int, windowStart time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateOneMinuteMetrics", ctx, appIds, windowStart)
	ret0, _ := ret[0].(error)
	return ret0
}

// AggregateOneMinuteMetrics indicates an expected call of AggregateOneMinuteMetrics.
func (mr *MockMetricServiceMockRecorder) AggregateOneMinuteMetrics(ctx, appIds, windowStart any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateOneMinuteMetrics", reflect.TypeOf((*MockMetricService)(nil).AggregateOneMinuteMetrics), ctx, appIds, windowStart)
}

// ClearMetrics mocks base method.
func (m *MockMetricService) ClearMetrics(ctx context.Context, data dtos.ClearMetrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearMetrics", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearMetrics indicates an expected call of ClearMetrics.
func (mr *MockMetricServiceMockRecorder) ClearMetrics(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearMetrics", reflect.TypeOf((*MockMetricService)(nil).ClearMetrics), ctx, data)
}

// CreateAppMetrics mocks base method.
func (m *MockMetricService) CreateAppMetrics(ctx context.Context, data []dtos.CreateAppMetric) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAppMetrics", ctx, data)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAppMetrics indicates an expected call of CreateAppMetrics.
func (mr *MockMetricServiceMockRecorder) CreateAppMetrics(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppMetrics", reflect.TypeOf((*MockMetricService)(nil).CreateAppMetrics), ctx, data)
}

// GetAggregatedAppMetricsByPeriod mocks base method.
func (m *MockMetricService) GetAggregatedAppMetricsByPeriod(ctx context.Context, appIds []int, periodType constants.PeriodType, startTime, endTime time.Time) ([]dtos.AggregatedAppMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAggregatedAppMetricsByPeriod", ctx, appIds, periodType, startTime, endTime)
	ret0, _ := ret[0].([]dtos.AggregatedAppMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAggregatedAppMetricsByPeriod indicates an expected call of GetAggregatedAppMetricsByPeriod.
func (mr *MockMetricServiceMockRecorder) GetAggregatedAppMetricsByPeriod(ctx, appIds, periodType, startTime, endTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAggregatedAppMetricsByPeriod", reflect.TypeOf((*MockMetricService)(nil).GetAggregatedAppMetricsByPeriod), ctx, appIds, periodType, startTime, endTime)
}

// GetAggregatedUniqueMetricsByApps mocks base method.
func (m *MockMetricService) GetAggregatedUniqueMetricsByApps(ctx context.Context, appIds []int, periodType constants.PeriodType, windowStart time.Time) ([]dtos.AggregatedMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAggregatedUniqueMetricsByApps", ctx, appIds, periodType, windowStart)
	ret0, _ := ret[0].([]dtos.AggregatedMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAggregatedUniqueMetricsByApps indicates an expected call of GetAggregatedUniqueMetricsByApps.
func (mr *MockMetricServiceMockRecorder) GetAggregatedUniqueMetricsByApps(ctx, appIds, periodType, windowStart any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAggregatedUniqueMetricsByApps", reflect.TypeOf((*MockMetricService)(nil).GetAggregatedUniqueMetricsByApps), ctx, appIds, periodType, windowStart)
}

// GetKeysCursor mocks base method.
func (m *MockMetricService) GetKeysCursor(ctx context.Context, cursor uint64, pattern string, count int) ([]string, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeysCursor", ctx, cursor, pattern, count)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetKeysCursor indicates an expected call of GetKeysCursor.
func (mr *MockMetricServiceMockRecorder) GetKeysCursor(ctx, cursor, pattern, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeysCursor", reflect.TypeOf((*MockMetricService)(nil).GetKeysCursor), ctx, cursor, pattern, count)
}

// GetMetrics mocks base method.
func (m *MockMetricService) GetMetrics(ctx context.Context, appId int, data *entities.GetMetricsData) (*entities.ResultMetricsGroups, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics", ctx, appId, data)
	ret0, _ := ret[0].(*entities.ResultMetricsGroups)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockMetricServiceMockRecorder) GetMetrics(ctx, appId, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*MockMetricService)(nil).GetMetrics), ctx, appId, data)
}

// IncrementMetrics mocks base method.
func (m *MockMetricService) IncrementMetrics(ctx context.Context, metrics dtos.MetricsMap, uniqueMetrics dtos.UniqueMetricsMap) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementMetrics", ctx, metrics, uniqueMetrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementMetrics indicates an expected call of IncrementMetrics.
func (mr *MockMetricServiceMockRecorder) IncrementMetrics(ctx, metrics, uniqueMetrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementMetrics", reflect.TypeOf((*MockMetricService)(nil).IncrementMetrics), ctx, metrics, uniqueMetrics)
}

// PublishMetricsToChannels mocks base method.
func (m *MockMetricService) PublishMetricsToChannels(ctx context.Context, createMetrics []dtos.CreateAppMetric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishMetricsToChannels", ctx, createMetrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishMetricsToChannels indicates an expected call of PublishMetricsToChannels.
func (mr *MockMetricServiceMockRecorder) PublishMetricsToChannels(ctx, createMetrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishMetricsToChannels", reflect.TypeOf((*MockMetricService)(nil).PublishMetricsToChannels), ctx, createMetrics)
}

// PublishToChannelBulk mocks base method.
func (m *MockMetricService) PublishToChannelBulk(ctx context.Context, data []dtos.PublishToChannel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishToChannelBulk", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishToChannelBulk indicates an expected call of PublishToChannelBulk.
func (mr *MockMetricServiceMockRecorder) PublishToChannelBulk(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishToChannelBulk", reflect.TypeOf((*MockMetricService)(nil).PublishToChannelBulk), ctx, data)
}

// SendChannelMessage mocks base method.
func (m *MockMetricService) SendChannelMessage(client *entities.WSClient, channelId, incomingMessage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendChannelMessage", client, channelId, incomingMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendChannelMessage indicates an expected call of SendChannelMessage.
func (mr *MockMetricServiceMockRecorder) SendChannelMessage(client, channelId, incomingMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendChannelMessage", reflect.TypeOf((*MockMetricService)(nil).SendChannelMessage), client, channelId, incomingMessage)
}

// SubscribeChannel mocks base method.
func (m *MockMetricService) SubscribeChannel(ctx context.Context, channelId string, handler func(string, string)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeChannel", ctx, channelId, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscribeChannel indicates an expected call of SubscribeChannel.
func (mr *MockMetricServiceMockRecorder) SubscribeChannel(ctx, channelId, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeChannel", reflect.TypeOf((*MockMetricService)(nil).SubscribeChannel), ctx, channelId, handler)
}

// TransferLiveMetricsToStreams mocks base method.
func (m *MockMetricService) TransferLiveMetricsToStreams(ctx context.Context, metricKeys []string) ([]dtos.TransferredMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferLiveMetricsToStreams", ctx, metricKeys)
	ret0, _ := ret[0].([]dtos.TransferredMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransferLiveMetricsToStreams indicates an expected call of TransferLiveMetricsToStreams.
func (mr *MockMetricServiceMockRecorder) TransferLiveMetricsToStreams(ctx, metricKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferLiveMetricsToStreams", reflect.TypeOf((*MockMetricService)(nil).TransferLiveMetricsToStreams), ctx, metricKeys)
}
