// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vekshinnikita/pulse_watch/internal/service (interfaces: AppService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_app_service.go -package=mock_service . AppService
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	entities "github.com/vekshinnikita/pulse_watch/internal/entities"
	models "github.com/vekshinnikita/pulse_watch/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAppService is a mock of AppService interface.
type MockAppService struct {
	ctrl     *gomock.Controller
	recorder *MockAppServiceMockRecorder
	isgomock struct{}
}

// MockAppServiceMockRecorder is the mock recorder for MockAppService.
type MockAppServiceMockRecorder struct {
	mock *MockAppService
}

// NewMockAppService creates a new mock instance.
func NewMockAppService(ctrl *gomock.Controller) *MockAppService {
	mock := &MockAppService{ctrl: ctrl}
	mock.recorder = &MockAppServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppService) EXPECT() *MockAppServiceMockRecorder {
	return m.recorder
}

// CheckApiKey mocks base method.
func (m *MockAppService) CheckApiKey(ctx context.Context, apiKey string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckApiKey", ctx, apiKey)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckApiKey indicates an expected call of CheckApiKey.
func (mr *MockAppServiceMockRecorder) CheckApiKey(ctx, apiKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckApiKey", reflect.TypeOf((*MockAppService)(nil).CheckApiKey), ctx, apiKey)
}

// CreateAndGetApp mocks base method.
func (m *MockAppService) CreateAndGetApp(ctx context.Context, data *entities.CreateAppData) (*models.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAndGetApp", ctx, data)
	ret0, _ := ret[0].(*models.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAndGetApp indicates an expected call of CreateAndGetApp.
func (mr *MockAppServiceMockRecorder) CreateAndGetApp(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAndGetApp", reflect.TypeOf((*MockAppService)(nil).CreateAndGetApp), ctx, data)
}

// CreateApiKey mocks base method.
func (m *MockAppService) CreateApiKey(ctx context.Context, data *entities.CreateApiKeyData) (*models.ApiKeyWithKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApiKey", ctx, data)
	ret0, _ := ret[0].(*models.ApiKeyWithKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateApiKey indicates an expected call of CreateApiKey.
func (mr *MockAppServiceMockRecorder) CreateApiKey(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApiKey", reflect.TypeOf((*MockAppService)(nil).CreateApiKey), ctx, data)
}

// CreateApp mocks base method.
func (m *MockAppService) CreateApp(ctx context.Context, data *entities.CreateAppData) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApp", ctx, data)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateApp indicates an expected call of CreateApp.
func (mr *MockAppServiceMockRecorder) CreateApp(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApp", reflect.TypeOf((*MockAppService)(nil).CreateApp), ctx, data)
}

// DeleteApp mocks base method.
func (m *MockAppService) DeleteApp(ctx context.Context, appId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteApp", ctx, appId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteApp indicates an expected call of DeleteApp.
func (mr *MockAppServiceMockRecorder) DeleteApp(ctx, appId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApp", reflect.TypeOf((*MockAppService)(nil).DeleteApp), ctx, appId)
}

// GetApp mocks base method.
func (m *MockAppService) GetApp(ctx context.Context, appId int) (*models.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApp", ctx, appId)
	ret0, _ := ret[0].(*models.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApp indicates an expected call of GetApp.
func (mr *MockAppServiceMockRecorder) GetApp(ctx, appId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApp", reflect.TypeOf((*MockAppService)(nil).GetApp), ctx, appId)
}

// GetAppApiKeysPaginated mocks base method.
func (m *MockAppService) GetAppApiKeysPaginated(ctx context.Context, p *entities.PaginationData, appId int) (*entities.PaginationResult[models.ApiKey], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppApiKeysPaginated", ctx, p, appId)
	ret0, _ := ret[0].(*entities.PaginationResult[models.ApiKey])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppApiKeysPaginated indicates an expected call of GetAppApiKeysPaginated.
func (mr *MockAppServiceMockRecorder) GetAppApiKeysPaginated(ctx, p, appId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppApiKeysPaginated", reflect.TypeOf((*MockAppService)(nil).GetAppApiKeysPaginated), ctx, p, appId)
}

// GetAppIds mocks base method.
func (m *MockAppService) GetAppIds(ctx context.Context) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppIds", ctx)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppIds indicates an expected call of GetAppIds.
func (mr *MockAppServiceMockRecorder) GetAppIds(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppIds", reflect.TypeOf((*MockAppService)(nil).GetAppIds), ctx)
}

// RevokeApiKey mocks base method.
func (m *MockAppService) RevokeApiKey(ctx context.Context, apiKeyId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeApiKey", ctx, apiKeyId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeApiKey indicates an expected call of RevokeApiKey.
func (mr *MockAppServiceMockRecorder) RevokeApiKey(ctx, apiKeyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeApiKey", reflect.TypeOf((*MockAppService)(nil).RevokeApiKey), ctx, apiKeyId)
}
