// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vekshinnikita/pulse_watch/internal/service (interfaces: AuthService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_auth_service.go -package=mock_service . AuthService
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	entities "github.com/vekshinnikita/pulse_watch/internal/entities"
	models "github.com/vekshinnikita/pulse_watch/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// CheckCurrentUserAnyPermission mocks base method.
func (m *MockAuthService) CheckCurrentUserAnyPermission(ctx context.Context, permissionCodes []string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCurrentUserAnyPermission", ctx, permissionCodes)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckCurrentUserAnyPermission indicates an expected call of CheckCurrentUserAnyPermission.
func (mr *MockAuthServiceMockRecorder) CheckCurrentUserAnyPermission(ctx, permissionCodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCurrentUserAnyPermission", reflect.TypeOf((*MockAuthService)(nil).CheckCurrentUserAnyPermission), ctx, permissionCodes)
}

// CheckCurrentUserPermission mocks base method.
func (m *MockAuthService) CheckCurrentUserPermission(ctx context.Context, permissionCode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCurrentUserPermission", ctx, permissionCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckCurrentUserPermission indicates an expected call of CheckCurrentUserPermission.
func (mr *MockAuthServiceMockRecorder) CheckCurrentUserPermission(ctx, permissionCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCurrentUserPermission", reflect.TypeOf((*MockAuthService)(nil).CheckCurrentUserPermission), ctx, permissionCode)
}

// CheckRoleAnyPermission mocks base method.
func (m *MockAuthService) CheckRoleAnyPermission(ctx context.Context, roleCode string, permissionCodes []string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRoleAnyPermission", ctx, roleCode, permissionCodes)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckRoleAnyPermission indicates an expected call of CheckRoleAnyPermission.
func (mr *MockAuthServiceMockRecorder) CheckRoleAnyPermission(ctx, roleCode, permissionCodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRoleAnyPermission", reflect.TypeOf((*MockAuthService)(nil).CheckRoleAnyPermission), ctx, roleCode, permissionCodes)
}

// CheckRolePermission mocks base method.
func (m *MockAuthService) CheckRolePermission(ctx context.Context, roleCode, permissionCode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRolePermission", ctx, roleCode, permissionCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckRolePermission indicates an expected call of CheckRolePermission.
func (mr *MockAuthServiceMockRecorder) CheckRolePermission(ctx, roleCode, permissionCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRolePermission", reflect.TypeOf((*MockAuthService)(nil).CheckRolePermission), ctx, roleCode, permissionCode)
}

// CreateAndGetUser mocks base method.
func (m *MockAuthService) CreateAndGetUser(ctx context.Context, createUser *entities.SignUpUser) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAndGetUser", ctx, createUser)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAndGetUser indicates an expected call of CreateAndGetUser.
func (mr *MockAuthServiceMockRecorder) CreateAndGetUser(ctx, createUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAndGetUser", reflect.TypeOf((*MockAuthService)(nil).CreateAndGetUser), ctx, createUser)
}

// CreateUser mocks base method.
func (m *MockAuthService) CreateUser(ctx context.Context, createUser *entities.SignUpUser) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, createUser)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockAuthServiceMockRecorder) CreateUser(ctx, createUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockAuthService)(nil).CreateUser), ctx, createUser)
}

// GenerateTokens mocks base method.
func (m *MockAuthService) GenerateTokens(ctx context.Context, user *models.User) (*entities.AuthTokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTokens", ctx, user)
	ret0, _ := ret[0].(*entities.AuthTokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTokens indicates an expected call of GenerateTokens.
func (mr *MockAuthServiceMockRecorder) GenerateTokens(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokens", reflect.TypeOf((*MockAuthService)(nil).GenerateTokens), ctx, user)
}

// GetCurrentUser mocks base method.
func (m *MockAuthService) GetCurrentUser(ctx context.Context) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentUser", ctx)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentUser indicates an expected call of GetCurrentUser.
func (mr *MockAuthServiceMockRecorder) GetCurrentUser(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentUser", reflect.TypeOf((*MockAuthService)(nil).GetCurrentUser), ctx)
}

// GetCurrentUserRole mocks base method.
func (m *MockAuthService) GetCurrentUserRole(ctx context.Context) (*models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentUserRole", ctx)
	ret0, _ := ret[0].(*models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentUserRole indicates an expected call of GetCurrentUserRole.
func (mr *MockAuthServiceMockRecorder) GetCurrentUserRole(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentUserRole", reflect.TypeOf((*MockAuthService)(nil).GetCurrentUserRole), ctx)
}

// GetUserById mocks base method.
func (m *MockAuthService) GetUserById(ctx context.Context, userId int) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", ctx, userId)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockAuthServiceMockRecorder) GetUserById(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockAuthService)(nil).GetUserById), ctx, userId)
}

// ParseAccessToken mocks base method.
func (m *MockAuthService) ParseAccessToken(ctx context.Context, accessToken string) (*entities.AccessTokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseAccessToken", ctx, accessToken)
	ret0, _ := ret[0].(*entities.AccessTokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseAccessToken indicates an expected call of ParseAccessToken.
func (mr *MockAuthServiceMockRecorder) ParseAccessToken(ctx, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseAccessToken", reflect.TypeOf((*MockAuthService)(nil).ParseAccessToken), ctx, accessToken)
}

// ParseToken mocks base method.
func (m *MockAuthService) ParseToken(ctx context.Context, accessToken string) (*entities.TokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseToken", ctx, accessToken)
	ret0, _ := ret[0].(*entities.TokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseToken indicates an expected call of ParseToken.
func (mr *MockAuthServiceMockRecorder) ParseToken(ctx, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseToken", reflect.TypeOf((*MockAuthService)(nil).ParseToken), ctx, accessToken)
}

// RefreshTokens mocks base method.
func (m *MockAuthService) RefreshTokens(ctx context.Context, refreshToken string) (*entities.AuthTokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTokens", ctx, refreshToken)
	ret0, _ := ret[0].(*entities.AuthTokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshTokens indicates an expected call of RefreshTokens.
func (mr *MockAuthServiceMockRecorder) RefreshTokens(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTokens", reflect.TypeOf((*MockAuthService)(nil).RefreshTokens), ctx, refreshToken)
}

// SignIn mocks base method.
func (m *MockAuthService) SignIn(ctx context.Context, signInUser *entities.SignInUser) (*entities.AuthTokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignIn", ctx, signInUser)
	ret0, _ := ret[0].(*entities.AuthTokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignIn indicates an expected call of SignIn.
func (mr *MockAuthServiceMockRecorder) SignIn(ctx, signInUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignIn", reflect.TypeOf((*MockAuthService)(nil).SignIn), ctx, signInUser)
}
