// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vekshinnikita/pulse_watch/internal/service (interfaces: LogsService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_logs_service.go -package=mock_service . LogsService
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	entities "github.com/vekshinnikita/pulse_watch/internal/entities"
	dtos "github.com/vekshinnikita/pulse_watch/internal/entities/dtos"
	models "github.com/vekshinnikita/pulse_watch/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockLogsService is a mock of LogsService interface.
type MockLogsService struct {
	ctrl     *gomock.Controller
	recorder *MockLogsServiceMockRecorder
	isgomock struct{}
}

// MockLogsServiceMockRecorder is the mock recorder for MockLogsService.
type MockLogsServiceMockRecorder struct {
	mock *MockLogsService
}

// NewMockLogsService creates a new mock instance.
func NewMockLogsService(ctrl *gomock.Controller) *MockLogsService {
	mock := &MockLogsService{ctrl: ctrl}
	mock.recorder = &MockLogsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogsService) EXPECT() *MockLogsServiceMockRecorder {
	return m.recorder
}

// CreateMetaVars mocks base method.
func (m *MockLogsService) CreateMetaVars(ctx context.Context, data []dtos.CreateMetaVar) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMetaVars", ctx, data)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMetaVars indicates an expected call of CreateMetaVars.
func (mr *MockLogsServiceMockRecorder) CreateMetaVars(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMetaVars", reflect.TypeOf((*MockLogsService)(nil).CreateMetaVars), ctx, data)
}

// GetExistingMetaVars mocks base method.
func (m *MockLogsService) GetExistingMetaVars(ctx context.Context, appId int, varCodes []string) ([]models.LogMetaVar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExistingMetaVars", ctx, appId, varCodes)
	ret0, _ := ret[0].([]models.LogMetaVar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExistingMetaVars indicates an expected call of GetExistingMetaVars.
func (mr *MockLogsServiceMockRecorder) GetExistingMetaVars(ctx, appId, varCodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExistingMetaVars", reflect.TypeOf((*MockLogsService)(nil).GetExistingMetaVars), ctx, appId, varCodes)
}

// GetMetaVarsPaginated mocks base method.
func (m *MockLogsService) GetMetaVarsPaginated(ctx context.Context, pagination *entities.PaginationData, appId *int) (*entities.PaginationResult[entities.LogMetaVarResult], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetaVarsPaginated", ctx, pagination, appId)
	ret0, _ := ret[0].(*entities.PaginationResult[entities.LogMetaVarResult])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetaVarsPaginated indicates an expected call of GetMetaVarsPaginated.
func (mr *MockLogsServiceMockRecorder) GetMetaVarsPaginated(ctx, pagination, appId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetaVarsPaginated", reflect.TypeOf((*MockLogsService)(nil).GetMetaVarsPaginated), ctx, pagination, appId)
}

// SaveLogs mocks base method.
func (m *MockLogsService) SaveLogs(ctx context.Context, logs []entities.EnrichedAppLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveLogs", ctx, logs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveLogs indicates an expected call of SaveLogs.
func (mr *MockLogsServiceMockRecorder) SaveLogs(ctx, logs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveLogs", reflect.TypeOf((*MockLogsService)(nil).SaveLogs), ctx, logs)
}

// SearchPaginatedLogs mocks base method.
func (m *MockLogsService) SearchPaginatedLogs(ctx context.Context, data *entities.SearchLogData) (*entities.PaginationResult[entities.EnrichedAppLog], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchPaginatedLogs", ctx, data)
	ret0, _ := ret[0].(*entities.PaginationResult[entities.EnrichedAppLog])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPaginatedLogs indicates an expected call of SearchPaginatedLogs.
func (mr *MockLogsServiceMockRecorder) SearchPaginatedLogs(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPaginatedLogs", reflect.TypeOf((*MockLogsService)(nil).SearchPaginatedLogs), ctx, data)
}

// SendLogs mocks base method.
func (m *MockLogsService) SendLogs(ctx context.Context, logs entities.AppLogs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLogs", ctx, logs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendLogs indicates an expected call of SendLogs.
func (mr *MockLogsServiceMockRecorder) SendLogs(ctx, logs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLogs", reflect.TypeOf((*MockLogsService)(nil).SendLogs), ctx, logs)
}
