// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vekshinnikita/pulse_watch/internal/service (interfaces: AlertService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_alert_service.go -package=mock_service . AlertService
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	entities "github.com/vekshinnikita/pulse_watch/internal/entities"
	dtos "github.com/vekshinnikita/pulse_watch/internal/entities/dtos"
	models "github.com/vekshinnikita/pulse_watch/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAlertService is a mock of AlertService interface.
type MockAlertService struct {
	ctrl     *gomock.Controller
	recorder *MockAlertServiceMockRecorder
	isgomock struct{}
}

// MockAlertServiceMockRecorder is the mock recorder for MockAlertService.
type MockAlertServiceMockRecorder struct {
	mock *MockAlertService
}

// NewMockAlertService creates a new mock instance.
func NewMockAlertService(ctrl *gomock.Controller) *MockAlertService {
	mock := &MockAlertService{ctrl: ctrl}
	mock.recorder = &MockAlertServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlertService) EXPECT() *MockAlertServiceMockRecorder {
	return m.recorder
}

// CreateAlertRule mocks base method.
func (m *MockAlertService) CreateAlertRule(ctx context.Context, data *entities.CreateAlertRule) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAlertRule", ctx, data)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAlertRule indicates an expected call of CreateAlertRule.
func (mr *MockAlertServiceMockRecorder) CreateAlertRule(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAlertRule", reflect.TypeOf((*MockAlertService)(nil).CreateAlertRule), ctx, data)
}

// CreateAlertsTask mocks base method.
func (m *MockAlertService) CreateAlertsTask(ctx context.Context, data []dtos.CreateAlert) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAlertsTask", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAlertsTask indicates an expected call of CreateAlertsTask.
func (mr *MockAlertServiceMockRecorder) CreateAlertsTask(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAlertsTask", reflect.TypeOf((*MockAlertService)(nil).CreateAlertsTask), ctx, data)
}

// CreateAndGetAlertRule mocks base method.
func (m *MockAlertService) CreateAndGetAlertRule(ctx context.Context, data *entities.CreateAlertRule) (*models.AlertRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAndGetAlertRule", ctx, data)
	ret0, _ := ret[0].(*models.AlertRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAndGetAlertRule indicates an expected call of CreateAndGetAlertRule.
func (mr *MockAlertServiceMockRecorder) CreateAndGetAlertRule(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAndGetAlertRule", reflect.TypeOf((*MockAlertService)(nil).CreateAndGetAlertRule), ctx, data)
}

// DeleteAlertRule mocks base method.
func (m *MockAlertService) DeleteAlertRule(ctx context.Context, ruleId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAlertRule", ctx, ruleId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAlertRule indicates an expected call of DeleteAlertRule.
func (mr *MockAlertServiceMockRecorder) DeleteAlertRule(ctx, ruleId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAlertRule", reflect.TypeOf((*MockAlertService)(nil).DeleteAlertRule), ctx, ruleId)
}

// GetAppRules mocks base method.
func (m *MockAlertService) GetAppRules(ctx context.Context, appId int) ([]models.AlertRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppRules", ctx, appId)
	ret0, _ := ret[0].([]models.AlertRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppRules indicates an expected call of GetAppRules.
func (mr *MockAlertServiceMockRecorder) GetAppRules(ctx, appId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppRules", reflect.TypeOf((*MockAlertService)(nil).GetAppRules), ctx, appId)
}

// GetAppRulesPaginated mocks base method.
func (m *MockAlertService) GetAppRulesPaginated(ctx context.Context, p *entities.PaginationData, appId int) (*entities.PaginationResult[models.AlertRule], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppRulesPaginated", ctx, p, appId)
	ret0, _ := ret[0].(*entities.PaginationResult[models.AlertRule])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppRulesPaginated indicates an expected call of GetAppRulesPaginated.
func (mr *MockAlertServiceMockRecorder) GetAppRulesPaginated(ctx, p, appId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppRulesPaginated", reflect.TypeOf((*MockAlertService)(nil).GetAppRulesPaginated), ctx, p, appId)
}

// GetFullAlertsByIds mocks base method.
func (m *MockAlertService) GetFullAlertsByIds(ctx context.Context, alertIds []int) ([]models.AlertFull, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFullAlertsByIds", ctx, alertIds)
	ret0, _ := ret[0].([]models.AlertFull)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFullAlertsByIds indicates an expected call of GetFullAlertsByIds.
func (mr *MockAlertServiceMockRecorder) GetFullAlertsByIds(ctx, alertIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFullAlertsByIds", reflect.TypeOf((*MockAlertService)(nil).GetFullAlertsByIds), ctx, alertIds)
}

// GetMetricsByRules mocks base method.
func (m *MockAlertService) GetMetricsByRules(ctx context.Context, rules []models.AlertRule) (dtos.MetricsByRuleIds, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricsByRules", ctx, rules)
	ret0, _ := ret[0].(dtos.MetricsByRuleIds)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetricsByRules indicates an expected call of GetMetricsByRules.
func (mr *MockAlertServiceMockRecorder) GetMetricsByRules(ctx, rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricsByRules", reflect.TypeOf((*MockAlertService)(nil).GetMetricsByRules), ctx, rules)
}

// GetRecentAlertsByRules mocks base method.
func (m *MockAlertService) GetRecentAlertsByRules(ctx context.Context, data *dtos.GetRecentAlerts) ([]models.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentAlertsByRules", ctx, data)
	ret0, _ := ret[0].([]models.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentAlertsByRules indicates an expected call of GetRecentAlertsByRules.
func (mr *MockAlertServiceMockRecorder) GetRecentAlertsByRules(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentAlertsByRules", reflect.TypeOf((*MockAlertService)(nil).GetRecentAlertsByRules), ctx, data)
}

// GetRule mocks base method.
func (m *MockAlertService) GetRule(ctx context.Context, ruleId int) (*models.AlertRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRule", ctx, ruleId)
	ret0, _ := ret[0].(*models.AlertRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRule indicates an expected call of GetRule.
func (mr *MockAlertServiceMockRecorder) GetRule(ctx, ruleId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRule", reflect.TypeOf((*MockAlertService)(nil).GetRule), ctx, ruleId)
}

// SetResolvedAlerts mocks base method.
func (m *MockAlertService) SetResolvedAlerts(ctx context.Context, alertIds []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetResolvedAlerts", ctx, alertIds)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetResolvedAlerts indicates an expected call of SetResolvedAlerts.
func (mr *MockAlertServiceMockRecorder) SetResolvedAlerts(ctx, alertIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetResolvedAlerts", reflect.TypeOf((*MockAlertService)(nil).SetResolvedAlerts), ctx, alertIds)
}

// UpdateAlertRule mocks base method.
func (m *MockAlertService) UpdateAlertRule(ctx context.Context, ruleId int, data *entities.UpdateAlertRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAlertRule", ctx, ruleId, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAlertRule indicates an expected call of UpdateAlertRule.
func (mr *MockAlertServiceMockRecorder) UpdateAlertRule(ctx, ruleId, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAlertRule", reflect.TypeOf((*MockAlertService)(nil).UpdateAlertRule), ctx, ruleId, data)
}
